spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
server:
  port: 8082
  servlet:
    context-path: /hibernate-with-h2
module:
  enabled: false